apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Values.app_name "-api" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print .Values.app_name "-api" }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "appinsights"
        dapr.io/app-id: {{ print .Values.app_name "-api" | quote }}
        dapr.io/log-level: "debug"
        dapr.io/http-max-request-size: "16"
        {{ print .Values.app_name "/config-hash" }}: {{ include (print $.Template.BasePath "/components.yaml") . | sha256sum }}
      labels:
        app: {{ print .Values.app_name "-api" }}
        aadpodidbinding: {{ .Values.msi_selector }} 
    spec:
      containers:
      - name: api
        image: {{ print .Values.acr_name ".azurecr.io/traduire/api:" .Values.commit_version }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: AZURE_COGS_REGION
          value: {{ .Values.cogs_region }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.app_name "-svc" }}
  labels:
    version: {{ .Values.commit_version | quote }} 
spec:
  selector:
    app: {{ print .Values.app_name "-api" }} 
  ports:
  - port: {{ .Values.service_port }}
    targetPort: 80
  type: NodePort
