apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Values.app_name "-onprocessing" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print .Values.app_name "-onprocessing" }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: {{ print .Values.app_name "-config" | quote }}
        dapr.io/app-id: {{ print .Values.app_name "-onprocessing" | quote }}
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        {{ print .Values.app_name "/config-hash" }}: {{ include (print $.Template.BasePath "/components.yaml") . | sha256sum }}
      labels:
        app: {{ print .Values.app_name "-onprocessing" }}
    spec:
      serviceAccountName: {{ print .Values.app_name "-dapr-reader" }}
      containers:
      - name: eventhandler
        image: {{ print .Values.acr_name ".azurecr.io/traduire/onprocessing.handler:" .Values.commit_version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: AZURE_COGS_REGION
          value: {{ .Values.cogs_region }}
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "traduire"
        effect: "NoSchedule"