app_name                                : ""
msi_client_id                           : ""
msi_resource_id                         : ""
keda_msi_client_id                      : ""
keda_msi_resource_id                    : ""
keyvault_name                           : ""
storage_name                            : ""
acr_name                                : ""
cogs_region                             : ""
app_insights_key                        : ""
frontend_uri                            : ""
msi_selector                            : "dapr-podidentity"
keda_selector                           : "keda-podidentity"
service_bus_connection_string_secret    : "sbconnection" 
storage_connection_string_secret        : "storagekey"
postgresql_connection_string_secret     : "postgresqlconnection"
service_bus_queue                       : "events"
storage_container                       : "mp3files"
utils_container                         : "bjd145/utils:latest"
commit_version                          : "1.0"
kong_api_secret                         : ""
kong_api_uri                            : ""
cert_email_address                      : "brian@bjdazure.tech"
delay_time_in_seconds                   : 5
service_port                            : 8081
service_bus_oncompleted_topic           : "ontranscription_completed"
service_bus_onpending_topic             : "ontranscription_processing"
service_bus_onstarted_topic             : "ontranscription_submitted" 
service_bus_onsleep_topic               : "ontranscription_sleep"