app_name                                : ""
msi_client_id                           : ""
msi_resource_id                         : ""
keyvault_name                           : ""
storage_name                            : ""
acr_name                                : ""
cogs_region                             : ""
app_insights_key                        : ""
msi_selector                            : "dapr-podidentity"
service_bus_connection_string_secret    : "sbconnection" 
storage_connection_string_secret        : "storagekey"
postgresql_connection_string_secret     : "postgresqlconnection"
service_bus_queue                       : "events"
storage_container                       : "mp3files"
utils_container                         : "bjd145/utils:latest"
commit_version                          : "1.0"
kong_api_secret                         : ""
kong_api_uri                            : ""